### ISSUE TITLE
Create team modal popup

### ISSUE THREAD

**Issue by derrekchow** [Impact-Labs/impact-labs.github.io#5]
- [ ] Update the team page by removing bios and adding them in a modal

When a team picture is clicked, a modal should appear with their bio.
![image](https://user-images.githubusercontent.com/17170744/50372528-d00c9280-059d-11e9-97dc-ca4daad865f4.png)

**Comment by derrekchow** [comment]
create a single modal just for now and we will create them procedurally later, don't create a modal for every team member, just do one properly styled one for now.

**Comment by yashgurditta** [comment]
Still need to change some colors including the backdrop of the modal.
Modals are functional but need to change some page styling.
