### ISSUE TITLE
Create FAQ dropdowns

### ISSUE THREAD

**Issue by derrekchow** [Impact-Labs/impact-labs.github.io#6]
Under FAQ for each section (Impact Labs, Summit, Coalition, etc), make each section toggle expand and retract on click. Icon should change according to toggle state (up <-> down arrow).

- [x] Use Unicode arrows ▲ and ▼ for icons.

![image](https://user-images.githubusercontent.com/17170744/50372502-4bba0f80-059d-11e9-9b23-a87efa27e44d.png)
## https://getbootstrap.com/docs/4.0/components/collapse/

Examples:
- http://tedxtoronto.com/faq/

**Comment by yashgurditta** [comment]
Still in progress, trying to figure out how to add toggle chevrons

**Comment by yashgurditta** [comment]
Added unicode arrows and ensured that they do not pop out on desktop. The feature is yet to be optimized for mobile.
