### ISSUE TITLE
my (Isabel Tripp) bio is messed up! 

### ISSUE THREAD

**Issue by tahitihat** [impact-labs/impact-labs.github.io#86]
hey everyone! I sent the Impact Labs website to a friend and they pointed out to me that my bio is truncated — it's because of a quote that isn't escaped. I was going to open a PR with the tiny copy change but I think your editing is restricted to collaborators.
![Screen Shot 2021-02-23 at 12 41 15 AM](https://user-images.githubusercontent.com/20799737/108807626-fa28b900-7548-11eb-87da-1e44d017e61e.png)

**Comment by tahitihat** [comment]
Feel free to add me to the repo and I can push the change up. If you'd rather not, I actually edited my bio a little which I would love to update if you (whoever *you* are) don't mind hehe — doesn't have any more quotes! 

_"My concerns about unmitigated tech development originate in my love of reading science fiction. I try not to lean into the fiction side too heavily, but today, there's no denying that tech ethics needs to be a larger part of the conversation. I joined Impact Labs because we're making a concerted effort to attract talent to the social impact technology space. And mission-driven tech is what makes me excited about the future. On a personal note, I've worked on projects related to hydroponic farming, conflict diamond trade mitigation, the neurobiology of tumor growth, and protecting Earth from asteroids! I'm on the hunt for the world''s best cinnamon bun so please send me leads. :)"_

**Comment by nikhilro** [comment]
![image](https://user-images.githubusercontent.com/22201788/108814444-a6799800-7567-11eb-9219-5cc35dee5394.png)


thanks for catching that and for the new bio!
